categories:
- Services
conversations:
- - what kind of services are there
  - which service exactly you want?
- - which is best food here
  - Special food is Junkha Bhakari, Tamda Padhara Rass.
- - what are available services
  - what kind service you want, be specific
